"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import clsx from "clsx";
import { useAcademyStore } from "@/lib/store/useAcademyStore";

const LIENS = [
 {href:"/dashboard",label:"🏠 Command Center",groupe:"jeu"},{href:"/jeu",label:"🎮 Jouer",groupe:"jeu"},{href:"/strategie",label:"🎯 Missions & décisions",groupe:"jeu"},{href:"/direction",label:"🎯 Direction",groupe:"jeu"},{href:"/destinees",label:"🧬 Destinées",groupe:"jeu"},
 {href:"/eleves",label:"👥 Élèves",groupe:"academie"},{href:"/classes",label:"🏫 Classes",groupe:"academie"},{href:"/notes",label:"📝 Notes",groupe:"academie"},{href:"/examens",label:"🏆 Examens",groupe:"academie"},{href:"/orientation",label:"🧭 Orientation",groupe:"academie"},
 {href:"/evolution",label:"📈 Évolution",groupe:"analyse"},{href:"/comparateur",label:"⚖️ Comparateur",groupe:"analyse"},{href:"/classements",label:"🥇 Classements",groupe:"analyse"},{href:"/statistiques",label:"📊 Statistiques",groupe:"analyse"},{href:"/eleves-a-suivre",label:"🔎 À suivre",groupe:"analyse"},
 {href:"/hall-of-fame",label:"🏛️ Hall of Fame",groupe:"monde"},{href:"/monde-vivant",label:"🌍 Monde vivant",groupe:"monde"},{href:"/heritage",label:"🧬 Héritage",groupe:"monde"},{href:"/civilisation",label:"🌐 Civilisation",groupe:"monde"},{href:"/carrieres",label:"💼 Carrières",groupe:"monde"},{href:"/finances",label:"💰 Finances",groupe:"monde"},
];
const GROUPES=["jeu","academie","analyse","monde"];
const TITRES:Record<string,string>={jeu:"Jouer",academie:"Académie",analyse:"Comprendre",monde:"Construire l'avenir"};
function etape(e:string){return ({T1:"Trimestre 1",T2:"Trimestre 2",T3:"Trimestre 3",examen:"Examens",orientation:"Orientation",annee_suivante:"Nouvelle année"} as Record<string,string>)[e]??e}
function Nav({close}:{close?:()=>void}){const path=usePathname(); const s=useAcademyStore(x=>x.session); const fav=s?.favoris?.length??0; return <>
 <div className="px-5 py-5 border-b border-white/10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-300 to-violet-500 flex items-center justify-center text-lg shadow-lg">✦</div><div><div className="text-[10px] uppercase tracking-[.2em] text-amber-300">Académie</div><div className="font-display text-lg text-white">Génération {s?.anneeDepart?.slice(0,4)??"2026"}</div></div></div><div className="mt-4 text-[11px] text-white/45">Ton établissement. Tes choix. Leur destin.</div></div>
 <nav className="flex-1 overflow-y-auto px-3 py-4 scrollbar-thin">{GROUPES.map(g=><div key={g} className="mb-5"><div className="px-3 mb-2 text-[9px] uppercase tracking-[.18em] text-white/35">{TITRES[g]}</div><div className="space-y-1">{LIENS.filter(x=>x.groupe===g).map(l=>{const active=path===l.href; return <Link key={l.href} href={l.href} onClick={close} className={clsx("block rounded-xl px-3 py-2.5 text-[13px] transition-all",active?"bg-white/10 text-white shadow-inner":"text-white/60 hover:bg-white/6 hover:text-white")}>{l.label}{l.href==="/eleves"&&fav>0?<span className="ml-2 text-[10px] text-amber-300">★{fav}</span>:null}</Link>})}</div></div>)}</nav>
 <div className="px-4 py-4 border-t border-white/10 text-[10px] text-white/45">{s?<><div className="text-white/70">{s.anneeCourante.libelle}</div><div className="mt-1">Étape : {etape(s.anneeCourante.etapeCourante)}</div></>:"Aucune partie"}</div>
 </>}
export default function Sidebar(){const [open,setOpen]=useState(false); const path=usePathname(); useEffect(()=>setOpen(false),[path]); return <><header className="md:hidden sticky top-0 z-30 safe-top bg-[#0b1020]/95 backdrop-blur text-white border-b border-white/10"><div className="h-14 px-4 flex items-center justify-between"><div className="font-display">Académie <span className="text-amber-300">✦</span></div><button onClick={()=>setOpen(true)} className="w-10 h-10 rounded-xl bg-white/8">☰</button></div></header>{open&&<div className="md:hidden fixed inset-0 z-50"><div className="absolute inset-0 bg-black/60" onClick={()=>setOpen(false)}/><aside className="absolute inset-y-0 left-0 w-[88%] max-w-sm bg-[#0b1020] text-white flex flex-col safe-top safe-bottom shadow-2xl"><div className="flex justify-end p-3"><button onClick={()=>setOpen(false)} className="w-9 h-9 rounded-lg bg-white/8">×</button></div><Nav close={()=>setOpen(false)}/></aside></div>}<aside className="hidden md:flex md:w-[270px] md:shrink-0 bg-[#0b1020] text-white md:flex-col sticky top-0 h-screen"><Nav/></aside></>}
