"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import PageHeader from "@/components/PageHeader";
import { useAcademyStore } from "@/lib/store/useAcademyStore";
import type { GameActionId } from "@/lib/models/types";

const money=(n:number)=>`${Math.round(n).toLocaleString("fr-FR")} FCFA`;
const actionCards:{id:GameActionId;icon:string;title:string;desc:string;cost:string;color:string}[]=[
 {id:"observer",icon:"🔎",title:"Observer",desc:"Révèle les signaux faibles d'un élève prometteur.",cost:"1 action",color:"cyan"},
 {id:"coacher",icon:"🧠",title:"Coacher",desc:"Fais progresser discipline, résilience et compétences.",cost:"1 action",color:"violet"},
 {id:"defi",icon:"⚡",title:"Lancer un défi",desc:"Prends un risque pour accélérer une destinée.",cost:"1 action",color:"amber"},
 {id:"bourse",icon:"💰",title:"Bourse de rupture",desc:"Supprime une contrainte financière qui menace un parcours.",cost:"1 action · 1 M FCFA",color:"green"},
 {id:"projet",icon:"🚀",title:"Projet étudiant",desc:"Transforme une idée en prototype et prépare l'innovation.",cost:"1 action · 0,5 M FCFA",color:"pink"},
 {id:"concours",icon:"🏆",title:"Concours stratégique",desc:"Expose un talent au regard du monde et augmente son réseau.",cost:"1 action",color:"blue"},
];
function score(e:any){return e.moyennes?.at(-1)?.moyenneGenerale??0}
export default function JeuPage(){
 const s=useAcademyStore(x=>x.session); const play=useAcademyStore(x=>x.executerActionJeu); const init=useAcademyStore(x=>x.initialiserJeu); const protect=useAcademyStore(x=>x.protegerEleveDirecteur);
 const [selected,setSelected]=useState(""); const [notice,setNotice]=useState("");
 useEffect(()=>{if(s && !s.jeu) init();},[s,init]);
 if(!s)return <div className="p-8"><div className="game-card p-8 max-w-xl"><h1 className="font-display text-3xl">Aucune partie</h1><Link href="/" className="inline-block mt-4 rounded-xl bg-ink text-white px-4 py-3">Créer une génération →</Link></div></div>;
 const d=s.directeur; const g=s.jeu; if(!d||!g)return <div className="p-8">Initialisation du jeu…</div>;
 const students=Object.values(s.eleves).filter(e=>["actif","redoublant","universite"].includes(e.statut)).sort((a,b)=>score(b)-score(a));
 const selectedStudent=students.find(e=>e.matricule===selected)??students[0];
 const current=g.objectives.find(o=>!o.complete)??g.objectives[g.objectives.length-1];
 const pct=current?Math.min(100,current.progression/current.cible*100):100;
 const doAction=(id:GameActionId)=>{const r=play(id,selectedStudent?.matricule);setNotice(r.message);};
 return <div className="max-w-[1500px] mx-auto p-4 md:p-7 lg:p-9 space-y-6">
  <PageHeader eyebrow={`🎮 Centre de jeu · Chapitre ${g.chapter}`} title={g.chapterTitle} description="Chaque clic est une décision. Chaque décision modifie une trajectoire. Ton objectif n'est pas de tout contrôler : c'est de faire les bons choix au bon moment."/>
  <section className="game-hero rounded-[28px] p-5 md:p-7 text-white relative overflow-hidden"><div className="absolute -right-24 -top-24 w-80 h-80 rounded-full bg-violet-500/25 blur-3xl"/><div className="absolute -left-20 -bottom-32 w-72 h-72 rounded-full bg-cyan-400/15 blur-3xl"/><div className="relative grid xl:grid-cols-[1fr_auto] gap-6 items-center"><div><div className="flex items-center gap-3 text-xs text-white/60"><span className="badge-live">● EN JEU</span><span>{s.anneeCourante.libelle}</span><span>·</span><span>{s.anneeCourante.etapeCourante}</span></div><div className="flex flex-wrap items-end gap-5 mt-5"><div><div className="text-[10px] uppercase tracking-[.18em] text-amber-300">Points</div><div className="font-display text-4xl">{g.score.toLocaleString("fr-FR")}</div></div><div><div className="text-[10px] uppercase tracking-[.18em] text-cyan-300">Combo</div><div className="font-display text-4xl">x{Math.max(1,g.combo)}</div></div><div><div className="text-[10px] uppercase tracking-[.18em] text-violet-300">Actions</div><div className="font-display text-4xl">{g.actionPoints}/{g.maxActionPoints}</div></div></div></div><div className="min-w-[260px] rounded-2xl bg-white/8 border border-white/10 p-4"><div className="text-[10px] uppercase tracking-[.18em] text-amber-300">🎯 Mission active</div><div className="font-semibold mt-2">{current?.titre??"Toutes les missions accomplies"}</div><div className="text-xs text-white/50 mt-1">{current?.description??"Tu as terminé ce chapitre."}</div>{current&&<><div className="flex justify-between text-[10px] text-white/45 mt-4"><span>{Math.round(current.progression)} / {current.cible}</span><b>{Math.round(pct)}%</b></div><div className="h-2 rounded-full bg-white/10 mt-1 overflow-hidden"><div className="h-full bg-gradient-to-r from-amber-300 to-violet-400" style={{width:`${pct}%`}}/></div></>}</div></div></section>
  {notice&&<div className="game-card p-4 border-violet-200 bg-violet-50 flex items-center justify-between"><div><b>✓ Conséquence :</b> <span className="text-slate">{notice}</span></div><button onClick={()=>setNotice("")} className="text-slate">×</button></div>}
  <section className="grid xl:grid-cols-[1.35fr_.65fr] gap-6">
   <div className="space-y-5"><div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><div className="section-kicker">Choisis ton intervention</div><h2 className="font-display text-2xl mt-1">6 actions, 6 façons de changer un destin</h2></div><select value={selectedStudent?.matricule??""} onChange={e=>setSelected(e.target.value)} className="rounded-xl border border-line bg-white px-3 py-2.5 text-sm max-w-full"><option value="">Élève cible : {selectedStudent?`${selectedStudent.prenom} ${selectedStudent.nom}`:"automatique"}</option>{students.slice(0,30).map(e=><option key={e.matricule} value={e.matricule}>{e.prenom} {e.nom} · {score(e).toFixed(1)}/20</option>)}</select></div>
    <div className="grid md:grid-cols-2 gap-4">{actionCards.map(a=>{const locked=!g.unlocked.includes(a.id);return <button key={a.id} disabled={locked||g.actionPoints<=0} onClick={()=>doAction(a.id)} className={`game-action ${a.color} text-left disabled:opacity-40 disabled:cursor-not-allowed`}><div className="flex items-start justify-between"><span className="text-3xl">{a.icon}</span><span className="text-[10px] rounded-full bg-white/70 px-2 py-1">{locked?"🔒 à débloquer":a.cost}</span></div><div className="font-display text-xl mt-4">{a.title}</div><div className="text-xs text-slate mt-1 leading-relaxed">{a.desc}</div><div className="mt-4 text-[11px] font-bold">{locked?"Progresse dans l'histoire":"JOUER →"}</div></button>})}</div>
    <div className="game-card p-5"><div className="section-kicker">Dernières conséquences</div><div className="mt-3 divide-y divide-line">{g.actionLog.slice(0,6).map(x=><div key={x.id} className="py-3 flex gap-3"><div className="w-8 h-8 rounded-lg bg-paper flex items-center justify-center">{actionCards.find(a=>a.id===x.action)?.icon??"✦"}</div><div className="flex-1"><div className="text-sm font-semibold">{x.titre}</div><div className="text-xs text-slate mt-1">{x.effet}</div></div><div className="text-xs font-bold">+{x.score}</div></div>)}{!g.actionLog.length&&<p className="text-sm text-slate">Tes premières décisions apparaîtront ici.</p>}</div></div>
   </div>
   <aside className="space-y-5"><div className="game-card p-5"><div className="section-kicker">👤 Élève ciblé</div><div className="flex items-center gap-3 mt-4"><div className="avatar-orb">{selectedStudent?.prenom?.[0]??"?"}</div><div><div className="font-display text-xl">{selectedStudent?`${selectedStudent.prenom} ${selectedStudent.nom}`:"—"}</div><div className="text-xs text-slate">{selectedStudent?.niveau} · {score(selectedStudent).toFixed(2)}/20</div></div></div>{selectedStudent&&<div className="grid grid-cols-2 gap-2 mt-5">{[["Assiduité",selectedStudent.assiduite],["Progression",selectedStudent.competences.progression],["Résilience",Math.round((d.psychologie[selectedStudent.matricule]?.resilience??0))],["Leadership",Math.round((d.psychologie[selectedStudent.matricule]?.leadership??0))]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-paper p-3"><div className="text-[10px] text-slate">{k}</div><div className="font-semibold mt-1">{Math.round(Number(v))}</div></div>)}</div>}{selectedStudent&&<button onClick={()=>{const ok=protect(selectedStudent.matricule);setNotice(ok?"Élève ajouté aux protégés de la Direction.":"Impossible de modifier cette protection.")}} className="w-full mt-4 rounded-xl border border-line px-4 py-3 text-xs font-semibold hover:border-ink">⭐ Protéger / retirer de la liste</button>}</div>
   <div className="game-card p-5"><div className="section-kicker">🏆 Objectifs du chapitre</div><div className="space-y-3 mt-4">{g.objectives.map(o=><div key={o.id} className={`rounded-xl p-3 border ${o.complete?"border-green-200 bg-green-50":"border-line bg-white"}`}><div className="flex justify-between gap-2"><span className="text-sm font-semibold">{o.complete?"✓ ":"○ "}{o.titre}</span><span className="text-[10px] font-bold">+{money(o.reward)}</span></div><div className="text-[11px] text-slate mt-1">{o.description}</div><div className="flex justify-between text-[10px] text-slate mt-2"><span>{Math.min(o.progression,o.cible)} / {o.cible}</span><span>{Math.round(Math.min(100,o.progression/o.cible*100))}%</span></div></div>)}</div></div>
   <div className="game-card p-5 bg-gradient-to-br from-amber-50 to-white"><div className="section-kicker">💡 Conseil du directeur</div><p className="font-display text-xl mt-2">Ne poursuis pas uniquement les meilleurs.</p><p className="text-xs text-slate mt-2 leading-relaxed">Les plus grandes histoires viennent parfois d'un élève moyen dont la résilience, la curiosité ou la créativité n'a pas encore été révélée.</p></div></aside>
  </section>
 </div>;
}
