"use client";
import Link from "next/link";
import PageHeader from "@/components/PageHeader";
import { useAcademyStore } from "@/lib/store/useAcademyStore";

const money=(n:number)=>`${Math.round(n).toLocaleString("fr-FR")} FCFA`;
const archetypes:Record<string,string>={leader:"Leader",expert:"Expert",entrepreneur:"Entrepreneur",chercheur:"Chercheur",humaniste:"Humaniste",explorateur:"Explorateur",artisan:"Bâtisseur"};
const facilityLabels:Record<string,string>={laboratoire:"Laboratoire",bibliotheque:"Bibliothèque",numerique:"Numérique",sport:"Sport",langues:"Langues",orientation:"Orientation",accompagnement:"Accompagnement"};

export default function StrategiePage(){
 const s=useAcademyStore(x=>x.session); const choisir=useAcademyStore(x=>x.resoudreEvenementDirecteur); const proteger=useAcademyStore(x=>x.protegerEleveDirecteur);
 if(!s)return <div className="p-8">Aucune session. <Link href="/">Créer une génération →</Link></div>;
 const d=s.directeur; if(!d)return null;
 const actifs=Object.values(s.eleves).filter(e=>["actif","redoublant","universite","diplome"].includes(e.statut));
 const candidats=[...actifs].sort((a,b)=>(b.moyennes.at(-1)?.moyenneGenerale??0)-(a.moyennes.at(-1)?.moyenneGenerale??0)).slice(0,12);
 return <div className="p-5 md:p-10 max-w-7xl">
  <PageHeader eyebrow={`Académie · ${s.modeJeu??"libre"}`} title="Le jeu des destinées" description="Décisions, événements, protégés, monde et conséquences : chaque année raconte une nouvelle histoire."/>
  <div className="grid md:grid-cols-5 gap-3 mb-8">{[["Budget",money(d.budget)],["Réputation",`${d.reputAcademie}/100`],["Score directeur",d.score],["Protégés",`${d.protectedStudents.length}/10`],["Cycle mondial",d.world.cycle]].map(([a,b])=><div key={a} className="border border-line bg-white/70 p-4"><div className="text-[10px] uppercase tracking-wide text-slate">{a}</div><div className="font-display text-xl mt-2">{b}</div></div>)}</div>
  <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-8">
   <section>
    {d.pendingEvent&&!d.pendingEvent.resolved?<div className="border-2 border-gold bg-gold-soft/20 p-6 mb-6"><div className="text-3xl">{d.pendingEvent.icon}</div><h2 className="font-display text-2xl mt-2">{d.pendingEvent.title}</h2><p className="text-sm text-slate mt-2 leading-relaxed">{d.pendingEvent.body}</p><div className="grid md:grid-cols-3 gap-3 mt-5">{d.pendingEvent.choices.map(c=><button key={c.id} onClick={()=>choisir(c.id)} className="text-left border border-line bg-white/80 p-4 hover:border-ink transition"><div className="font-medium">{c.label}</div><div className="text-xs text-slate mt-1">{c.description}</div><div className="text-[11px] mt-3 text-ink">→ {c.consequence}</div></button>)}</div></div>:<div className="border border-line bg-white/70 p-5 mb-6"><div className="text-[10px] uppercase tracking-wide text-slate">Prochaine scène</div><div className="font-display text-xl mt-1">Faites avancer la simulation pour révéler la suite.</div><p className="text-sm text-slate mt-2">Les choix deviennent des traces dans l'histoire de la génération.</p></div>}
    <div className="border border-line bg-white/70 p-5 mb-6"><div className="flex justify-between items-start gap-4"><div><div className="text-[10px] uppercase tracking-wide text-slate">📖 Mode histoire</div><h2 className="font-display text-xl mt-1">Chapitre {d.story.chapitre} · {d.story.titre}</h2></div><span className="text-xs border border-gold px-2 py-1">{d.story.objectifs.filter(o=>o.complete).length}/{d.story.objectifs.length} accomplis</span></div><div className="grid md:grid-cols-3 gap-3 mt-5">{d.story.objectifs.map(o=><div key={o.id} className={`border p-3 ${o.complete?"border-gold bg-gold-soft/20":"border-line bg-white"}`}><div className="text-sm font-medium">{o.complete?"✓ ":""}{o.titre}</div><div className="text-[11px] text-slate mt-1">{o.description}</div><div className="text-[11px] mt-2">{Math.round(o.progression)} / {o.cible}</div></div>)}</div></div>
    <div className="border border-line bg-white/70 p-5 mb-6"><div className="text-[10px] uppercase tracking-wide text-slate">🏫 Capital de l'Académie</div><p className="text-xs text-slate mt-1">Des infrastructures fortes donnent un avantage durable aux élèves.</p><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-5">{Object.entries(d.facilities).map(([k,v])=><div key={k}><div className="flex justify-between text-xs"><span>{facilityLabels[k]??k}</span><b>{v}</b></div><div className="h-1.5 bg-line/40 mt-2"><div className="h-full bg-ink" style={{width:`${v}%`}}/></div></div>)}</div></div>
    <div className="border border-line bg-white/70 p-5 mb-6"><div className="text-[10px] uppercase tracking-wide text-slate">🌍 Monde</div><h2 className="font-display text-xl mt-1">{d.world.headline}</h2><div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-4 text-xs">{[["Économie",d.world.economie],["Technologie",d.world.technologie],["Emploi",d.world.emploi],["International",d.world.international],["Coût de vie",d.world.coutVie]].map(([k,v])=><div key={k}><div className="text-slate">{k}</div><div className="font-medium mt-1">{Math.round(Number(v))}</div></div>)}</div></div>
    <h2 className="font-display text-xl mb-3">⭐ Mes protégés potentiels</h2><div className="grid md:grid-cols-2 gap-3">{candidats.map(e=>{const p=d.psychologie[e.matricule];const prot=d.protectedStudents.includes(e.matricule);return <div key={e.matricule} className="border border-line bg-white/70 p-4 flex items-center justify-between gap-3"><div><div className="font-medium">{e.prenom} {e.nom}</div><div className="text-xs text-slate">{e.matricule} · {e.moyennes.at(-1)?.moyenneGenerale?.toFixed(2)??"—"}/20</div><div className="text-[11px] text-slate mt-1">Projection : {p?`${archetypes[(Object.entries({leader:p.leadership,expert:p.discipline,entrepreneur:p.creativite,chercheur:p.intelligenceAnalytique,humaniste:p.communication,explorateur:p.curiosite,artisan:50}).sort((a,b)=>b[1]-a[1])[0]?.[0]??"artisan")]}`:"—"}</div></div><button onClick={()=>proteger(e.matricule)} className={`text-xs px-3 py-2 border ${prot?"border-gold bg-gold-soft/30":"border-line hover:border-ink"}`}>{prot?"★ Protégé":"Protéger"}</button></div>})}</div>
   </section>
   <aside><h2 className="font-display text-xl mb-3">🏆 Missions</h2><div className="space-y-3">{d.missions.map(m=><div key={m.id} className="border border-line bg-white/70 p-4"><div className="flex justify-between"><div className="font-medium">{m.completed?"✓ ":""}{m.title}</div><div className="text-xs">+{money(m.reward)}</div></div><div className="text-xs text-slate mt-1">{m.description}</div><div className="h-2 bg-line/40 mt-3"><div className="h-full bg-ink" style={{width:`${Math.min(100,m.progress/m.target*100)}%`}}/></div><div className="text-[11px] text-slate mt-1">{m.progress.toFixed(m.id==="major"?2:0)} / {m.target}</div></div>)}</div>
    <h2 className="font-display text-xl mt-8 mb-3">📖 Chronique</h2><div className="border border-line bg-white/70 divide-y divide-line">{d.journal.slice(0,12).map(j=><div className="p-4" key={j.id}><div className="text-[10px] uppercase tracking-wide text-slate">{j.annee}</div><div className="font-medium mt-1">{j.title}</div><div className="text-xs text-slate mt-1">{j.body}</div></div>)}</div>
   </aside>
  </div>
 </div>;
}
