"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import PageHeader from "@/components/PageHeader";
import StatCard from "@/components/StatCard";
import { useAcademyStore } from "@/lib/store/useAcademyStore";
import { getCivilizationState } from "@/lib/engines/civilisation";
const fcfa=(n:number)=>`${Math.round(n).toLocaleString("fr-FR")} FCFA`;
export default function CivilisationPage(){
 const session=useAcademyStore(s=>s.session), simuler=useAcademyStore(s=>s.simulerCivilisation), simulerN=useAcademyStore(s=>s.simulerCivilisationNAnnees); const [message,setMessage]=useState("");
 const state=useMemo(()=>session?getCivilizationState(session):null,[session]);
 if(!session||!state)return <div className="p-6">Aucune session active. <Link href="/" className="underline">Créer une session</Link>.</div>;
 const companies=Object.values(state.entreprises).sort((a,b)=>b.valeur-a.valeur).slice(0,12), families=Object.values(state.familles).sort((a,b)=>b.influence-a.influence).slice(0,12), universities=Object.values(state.universites).sort((a,b)=>b.prestige-a.prestige), events=state.evenements.slice(0,10);
 return <div className="p-5 md:p-10 max-w-7xl"><PageHeader eyebrow="🌐 CIVILISATION" title="Le monde ne s'arrête jamais" description="Une couche stratégique sur plusieurs décennies : familles, entreprises, universités, transmissions, crises et innovations produisent une histoire collective." />
 <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8"><StatCard label="Indice civilisation" value={`${state.indiceCivilisation}/100`} accent="gold"/><StatCard label="Ère" value={state.titreEre.replace("L'âge de ","")} accent="forest"/><StatCard label="Patrimoine global" value={fcfa(state.patrimoineGlobal)} accent="burgundy"/><StatCard label="Influence globale" value={`${state.influenceGlobale}/100`} accent="gold"/></div>
 <div className="border border-line bg-ink text-paper p-5 mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.18em] text-gold">{state.annee} · {state.era}</div><div className="font-display text-2xl mt-1">{state.titreEre}</div><div className="text-sm text-paper/65 mt-1">{state.anneesSimulees} année(s) simulée(s) · {state.successionRealisee} transmission(s) d'entreprise</div></div><div className="flex gap-2 flex-wrap"><button onClick={()=>{simuler();setMessage("Une nouvelle année civilisationnelle a été simulée.")}} className="bg-gold text-ink px-4 py-2 text-sm font-medium">Simuler 1 an →</button><button onClick={()=>{const n=simulerN(5);setMessage(`${n} années prospectives simulées.`)}} className="border border-paper/30 px-4 py-2 text-sm">+ 5 ans</button></div></div>
 {message&&<div className="text-sm text-slate mb-6">{message}</div>}
 <div className="grid grid-cols-3 gap-4 mb-10"><div className="border border-line bg-white/60 p-5"><div className="text-[10px] uppercase tracking-[.18em] text-gold">Familles</div><div className="font-display text-3xl mt-2">{Object.keys(state.familles).length}</div><div className="text-xs text-slate mt-1">lignées suivies</div></div><div className="border border-line bg-white/60 p-5"><div className="text-[10px] uppercase tracking-[.18em] text-gold">Entreprises</div><div className="font-display text-3xl mt-2">{Object.keys(state.entreprises).length}</div><div className="text-xs text-slate mt-1">groupes dans l'écosystème</div></div><div className="border border-line bg-white/60 p-5"><div className="text-[10px] uppercase tracking-[.18em] text-gold">Innovations</div><div className="font-display text-3xl mt-2">{state.compteurInnovations}</div><div className="text-xs text-slate mt-1">accélérations technologiques</div></div></div>
 <div className="grid lg:grid-cols-2 gap-8"><section><div className="text-[10px] uppercase tracking-[.18em] text-gold mb-1">Capital économique</div><h2 className="font-display text-2xl mb-3">Entreprises et transmissions</h2><div className="border border-line bg-white/60 divide-y divide-line">{companies.length===0?<div className="p-5 text-sm text-slate">Les premières entreprises apparaîtront lorsque les élèves deviendront entrepreneurs.</div>:companies.map(e=><div key={e.id} className="px-4 py-4"><div className="flex justify-between gap-3"><div><div className="font-medium text-sm">{e.nom}</div><div className="text-xs text-slate">{e.secteur} · {e.emplois} emplois · génération dirigeante {e.generationDirigeante}</div></div><div className="text-right text-xs"><div>{fcfa(e.valeur)}</div><div className="text-gold uppercase">{e.statut}</div></div></div></div>)}</div></section>
 <section><div className="text-[10px] uppercase tracking-[.18em] text-gold mb-1">Capital social</div><h2 className="font-display text-2xl mb-3">Familles et dynasties</h2><div className="border border-line bg-white/60 divide-y divide-line">{families.length===0?<div className="p-5 text-sm text-slate">Les dynasties apparaîtront lorsque les relations et patrimoines se consolideront.</div>:families.map(f=><div key={f.id} className="px-4 py-4"><div className="flex justify-between"><div className="font-medium text-sm">{f.nom}</div><span className="text-[10px] uppercase text-gold">{f.statut}</span></div><div className="text-xs text-slate mt-1">Influence {f.influence}/100 · patrimoine {fcfa(f.patrimoine)} · {f.membres} membre(s)</div></div>)}</div></section></div>
 <section className="mt-8"><div className="text-[10px] uppercase tracking-[.18em] text-gold mb-1">Universités concurrentes</div><h2 className="font-display text-2xl mb-3">Le marché du talent</h2><div className="grid md:grid-cols-2 gap-3">{universities.map(u=><div key={u.id} className="border border-line bg-white/60 p-4"><div className="flex justify-between"><div className="font-medium text-sm">{u.nom}</div><span className="text-sm">{u.prestige}/100</span></div><div className="mt-3 h-2 bg-line/50"><div className="h-full bg-ink" style={{width:`${u.prestige}%`}}/></div><div className="text-xs text-slate mt-2">Recherche {u.recherche} · {u.bourses} bourses · {u.recrutements} recrutements</div></div>)}</div></section>
 <section className="mt-8"><div className="text-[10px] uppercase tracking-[.18em] text-gold mb-1">Chronique mondiale</div><h2 className="font-display text-2xl mb-3">Les événements qui changent la civilisation</h2><div className="border border-line bg-white/60 divide-y divide-line">{events.length===0?<div className="p-5 text-sm text-slate">Aucun événement historique pour le moment.</div>:events.map(e=><div key={e.id} className="px-4 py-4"><div className="text-[10px] uppercase text-gold">{e.annee} · {e.categorie}</div><div className="font-medium text-sm mt-1">{e.titre}</div><div className="text-xs text-slate mt-1">{e.texte}</div></div>)}</div></section>
 </div>;
}
